import draxar from "./images/gladiators/draxar_thraex.jpeg";
import pravus from "./images/gladiators/pravus_secutor.jpeg";
import sagax from "./images/gladiators/sagax_secutor.jpeg";
import phanemeos from "./images/gladiators/phanemeos_retiarius.jpeg";
import xenatheles from "./images/gladiators/xenatheles_dimachaerus.jpeg";
import kyracros from "./images/gladiators/kyracros_hoplomachus.jpeg";
import belliatus from "./images/gladiators/belliatus_murmillo.jpeg";
import manuxes from "./images/gladiators/manuxes_thraex.jpeg";
import faedexus from "./images/gladiators/faedexus_hoplomachus.jpeg";
import antheles from "./images/gladiators/antheles_retiarius.jpeg";
import seera from "./images/gladiators/seera_gladriatrix.jpeg";
import caedes from "./images/gladiators/caedes_dimachaerus.jpeg";
import braxus from "./images/gladiators/braxus_murmillo.jpeg";
import laetus from "./images/gladiators/laetus_thraex.jpeg";
import dakhar from "./images/gladiators/dakhar_hoplomachus.jpeg";

const gladiators = [
  {
    name: "Draxar",
    type: "Thraex",
    style: "balanced",
    nation: "German",
    cost: 5,
    img: draxar,
    atk: 9,
    currentatk: 9,
    hp: 5,
    fhp: 5,
    spd: 5,
    def: 8,
    bdef: 0,
    currentdef: 8,
    atk_w: [],
    def_w: [],
    isRightAtk: 0,
    isRightDef: 0,
  },
  {
    name: "Pravus",
    type: "Secutor",
    nation: "Gaul",
    style: "defensive",
    cost: 2,
    img: pravus,
    atk: 7,
    currentatk: 7,
    hp: 5,
    fhp: 5,
    spd: 3,
    def: 9,
    currentdef: 9,
    atk_w: [],
    def_w: [],
    isRightAtk: 0,
    isRightDef: 0,
  },
  {
    name: "Sagax",
    type: "Secutor",
    nation: "Gaul",
    style: "defensive",
    cost: 2,
    img: sagax,
    atk: 7,
    currentatk: 7,
    hp: 4,
    fhp: 4,
    spd: 4,
    def: 8,
    currentdef: 8,
    atk_w: [],
    def_w: [],
    isRightAtk: 0,
    isRightDef: 0,
  },
  {
    name: "Phanemeos",
    type: "Retiarius",
    nation: "Egyptian",
    style: "aggressive",
    img: phanemeos,
    cost: 3,
    atk: 9,
    currentatk: 9,
    hp: 4,
    fhp: 4,
    spd: 8,
    def: 5,
    currentdef: 5,
    atk_w: [],
    def_w: [],
    isRightAtk: 0,
    isRightDef: 0,
  },
  {
    name: "Xenatheles",
    type: "Dimachaerus",
    nation: "Thracian",
    style: "aggressive",
    img: xenatheles,
    cost: 4,
    atk: 10,
    currentatk: 10,
    hp: 4,
    fhp: 4,
    spd: 7,
    def: 6,
    currentdef: 6,
    atk_w: [],
    def_w: [],
    isRightAtk: 0,
    isRightDef: 0,
    isDamaged: false,
  },
  {
    name: "Kyracros",
    type: "Hoplomachus",
    nation: "Numidian",
    style: "aggressive",
    img: kyracros,
    cost: 3,
    atk: 9,
    currentatk: 9,
    hp: 4,
    fhp: 4,
    spd: 7,
    atk_w: [],
    def: 6,
    currentdef: 6,
    def_w: [],
    isRightAtk: 0,
    isRightDef: 0,
  },
  {
    name: "Laetus",
    type: "Thraex",
    nation: "Roman",
    img: laetus,
    cost: 3,
    style: "balanced",
    atk: 8,
    currentatk: 8,
    hp: 4,
    fhp: 4,
    spd: 6,
    def: 8,
    currentdef: 8,
    atk_w: [],
    def_w: [],
    isRightAtk: 0,
    isRightDef: 0,
    isBonus: false,
  },
  {
    name: "Belliatus",
    type: "Murmillo",
    nation: "Roman",
    style: "defensive",
    img: belliatus,
    cost: 3,
    atk: 6,
    currentatk: 6,
    hp: 5,
    fhp: 5,
    spd: 2,
    def: 10,
    currentdef: 10,
    atk_w: [],
    def_w: [],
    isRightAtk: 0,
    isRightDef: 0,
  },
  {
    name: "Manuxes",
    type: "Thraex",
    nation: "Gaul",
    style: "balanced",
    img: manuxes,
    cost: 3,
    atk: 7,
    currentatk: 7,
    hp: 4,
    fhp: 4,
    spd: 6,
    def: 8,
    currentdef: 8,
    atk_w: [],
    def_w: [],
    isRightAtk: 0,
    isRightDef: 0,
  },
  {
    name: "Faedexus",
    type: "Hoplomachus",
    nation: "Thracian",
    style: "aggressive",
    img: faedexus,
    cost: 2,
    currentatk: 8,
    atk: 8,
    hp: 4,
    fhp: 4,
    spd: 6,
    def: 6,
    currentdef: 6,
    atk_w: [],
    isRightAtk: 0,
    isRightDef: 0,

    def_w: [],
  },
  {
    name: "Antheles",
    type: "Retiarius",
    nation: "Greek",
    style: "aggressive",
    cost: 4,
    img: antheles,
    currentatk: 10,
    atk: 10,
    hp: 4,
    fhp: 4,
    spd: 7,
    def: 5,
    currentdef: 5,
    atk_w: [],
    def_w: [],
    isRightAtk: 0,
    isRightDef: 0,
  },
  {
    name: "Seera",
    type: "Gladriatrix",
    nation: "German",
    style: "balanced",
    img: seera,
    cost: 4,
    atk: 8,
    currentatk: 8,
    hp: 4,
    fhp: 4,
    spd: 8,
    def: 7,
    currentdef: 7,
    atk_w: [],
    def_w: [],
    isRightAtk: 0,
    isRightDef: 0,
  },
  {
    name: "Caedes",
    type: "Dimachaerus",
    nation: "Celt",
    style: "aggressive",
    img: caedes,
    cost: 5,
    atk: 11,
    currentatk: 11,
    hp: 4,
    fhp: 4,
    spd: 5,
    def: 6,
    currentdef: 6,
    atk_w: [],
    def_w: [],
    isRightAtk: 0,
    isRightDef: 0,
    isUlt: false,
  },
  {
    name: "Braxus",
    type: "Murmillo",
    nation: "Thracian",
    style: "defensive",
    img: braxus,
    cost: 3,
    atk: 7,
    currentatk: 7,
    hp: 4,
    fhp: 4,
    spd: 5,
    def: 9,
    currentdef: 9,
    atk_w: [],
    def_w: [],
    isRightAtk: 0,
    isRightDef: 0,
  },
  {
    name: "Dakhar",
    type: "Hoplomachus",
    nation: "Syrian",
    style: "aggressive",
    cost: 4,
    img: dakhar,
    atk: 9,
    currentatk: 9,
    hp: 4,
    fhp: 4,
    spd: 6,
    def: 7,
    currentdef: 7,
    atk_w: [],
    def_w: [],
    isRightAtk: 0,
    isRightDef: 0,
  },
];

export default gladiators;
